language: node_js
node_js: 0.11
install:
  - gem install mdl
  - npm install -g markdownlint-cli remark-cli remark-lint
script:
  - mdl -c ./.mdlrc README.md
  - markdownlint -c ./.markdownlint.json README.md
  - touch package.json
  - remark --config=./.remarkrc.js --frail --no-stdout -u lint ./README.md
  - remark ./README.md > ./README.md.new
  - sed -i 's/&lt;/</g' README.md.new
  - sed -i 's:\\\\:\\:g' README.md.new
  - sed -i 's/&#x3A;/:/g' README.md.new
  - sed -i 's/\\\*\\\*/**/;s/\\\*\([^*]*\)$/*\1/g' README.md.new
  - mv README.md.new README.md
  - git diff README.md
